# Generated by Django 4.2.11 on 2024-07-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpackages',
            name='slug',
        ),
    ]
