# Generated by Django 4.2.11 on 2024-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_subpackages_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpackages',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
